export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const CHAT_REQUEST = "CHAT_REQUEST";
export const CHAT_SUCCESS = "CHAT_SUCCESS";
export const CHAT_FAIL = "CHAT_FAIL";

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";

export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";
export const GET_CHAT_RESET = "GET_CHAT_RESET";

export const RENAME_GROUP_CHAT_REQUEST = "RENAME_GROUP_CHAT_REQUEST";
export const RENAME_GROUP_CHAT_SUCCESS = "RENAME_GROUP_CHAT_SUCCESS";
export const RENAME_GROUP_CHAT_FAIL = "RENAME_GROUP_CHAT_FAIL";

export const ADDTO_GROUP_CHAT_REQUEST = "ADDTO_GROUP_CHAT_REQUEST";
export const ADDTO_GROUP_CHAT_SUCCESS = "ADDTO_GROUP_CHAT_SUCCESS";
export const ADDTO_GROUP_CHAT_FAIL = "ADDTO_GROUP_CHAT_FAIL";

export const REMOVE_FROM_GROUP_CHAT_REQUEST = "REMOVE_FROM_GROUP_CHAT_REQUEST";
export const REMOVE_FROM_GROUP_CHAT_SUCCESS = "REMOVE_FROM_GROUP_CHAT_SUCCESS";
export const REMOVE_FROM_GROUP_CHAT_FAIL = "REMOVE_FROM_GROUP_CHAT_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL";

export const SET_MESSAGE_LOADING = "SET_MESSAGE_LOADING";
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
